export const CONFIG = {
  BOARD_WIDTH: 360,
  BOARD_HEIGHT: 580,
  WALL_THICKNESS: 12,
  SHELF_HEIGHT: 14,
  SHELF_Y_START: 0.72,
  SHELF_TRAVEL: 100,
  SHELF_SPEED: 1.2,
  DROP_ZONE_Y: 60,
  PAYOUT_ZONE_Y: 560,
  COIN_SPAWN_X_CENTER: 180,
  GRAVITY: 1.8,
  MAX_COINS_ON_BOARD: 60,
  COMBO_WINDOW_MS: 1800,
  BOMB_FUSE_MS: 1200,
  STARTING_DROPS: 12,
  STARTING_TARGET: 20,
  TARGET_INCREMENT: 8,
  SHOP_CHOICES: 3,
};

export const COIN_DEFS = {
  normal: {
    typeId: 'normal' as const,
    name: 'Normal Coin',
    color: '#d7b94c',
    glowColor: '#ffe066',
    radius: 13,
    density: 0.0018,
    restitution: 0.18,
    friction: 0.08,
    baseValue: 1,
    payoutValue: 1,
    weight: 100,
    description: 'A reliable coin with standard payout.',
  },
  heavy: {
    typeId: 'heavy' as const,
    name: 'Heavy Coin',
    color: '#8a9ab0',
    glowColor: '#c0ccdd',
    radius: 16,
    density: 0.0045,
    restitution: 0.08,
    friction: 0.14,
    baseValue: 1,
    payoutValue: 1,
    weight: 60,
    description: 'Heavier coin that shoves stacks hard.',
  },
  bomb: {
    typeId: 'bomb' as const,
    name: 'Bomb Coin',
    color: '#cc4444',
    glowColor: '#ff8888',
    radius: 14,
    density: 0.002,
    restitution: 0.12,
    friction: 0.1,
    baseValue: 0,
    payoutValue: 2,
    weight: 25,
    description: 'Explodes after landing, launching nearby coins.',
  },
  lucky: {
    typeId: 'lucky' as const,
    name: 'Lucky Coin',
    color: '#44bb66',
    glowColor: '#88ffaa',
    radius: 13,
    density: 0.0017,
    restitution: 0.22,
    friction: 0.07,
    baseValue: 1,
    payoutValue: 2,
    weight: 20,
    description: 'Pays extra gold when exiting center lane.',
  },
};

export const ITEM_DEFS = {
  magnet: {
    typeId: 'magnet' as const,
    name: 'Magnet',
    icon: '🧲',
    description: 'Coins near the edge drift forward every 3 seconds.',
    cost: 12,
    rarity: 'common' as const,
  },
  multiplierTray: {
    typeId: 'multiplierTray' as const,
    name: 'Multiplier Tray',
    icon: '✖️',
    description: 'Every 5th payout gives double score.',
    cost: 18,
    rarity: 'rare' as const,
  },
  bombPolish: {
    typeId: 'bombPolish' as const,
    name: 'Bomb Polish',
    icon: '💥',
    description: 'Bombs explode with a 30% larger radius.',
    cost: 14,
    rarity: 'common' as const,
  },
  luckyLip: {
    typeId: 'luckyLip' as const,
    name: 'Lucky Lip',
    icon: '🍀',
    description: 'Center-lane payouts gain +2 bonus gold.',
    cost: 15,
    rarity: 'rare' as const,
  },
  heavyMint: {
    typeId: 'heavyMint' as const,
    name: 'Heavy Mint',
    icon: '⚡',
    description: 'Heavy coins deal 20% more push force.',
    cost: 16,
    rarity: 'common' as const,
  },
};

export type CoinTypeId = keyof typeof COIN_DEFS;
export type ItemTypeId = keyof typeof ITEM_DEFS;
